
from typing import Dict, Any, Optional, List
import os, time, re
from rdflib.namespace import RDFS, RDF, XSD, Namespace
from rdflib import URIRef, Literal

PROV = Namespace("http://www.w3.org/ns/prov#")
OCXP = Namespace("http://ontocodex.ai/prov#")
OBOIO = Namespace("http://www.geneontology.org/formats/oboInOwl#")

def _slug(label: str) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "_", label.strip())
    return s.strip("_") or "Entity"

TEMPLATE_PY = """# Auto-generated by OntoCodex EnrichmentScriptAgent (v3.0)
from rdflib import Graph, URIRef, Literal, Namespace
from rdflib.namespace import RDF, RDFS, XSD
PROV = Namespace("http://www.w3.org/ns/prov#")
OCXP = Namespace("http://ontocodex.ai/prov#")
OBOIO = Namespace("http://www.geneontology.org/formats/oboInOwl#")

g = Graph()
g.bind("prov", PROV); g.bind("ocxp", OCXP); g.bind("rdfs", RDFS); g.bind("oboInOwl", OBOIO)

g.parse("{doid_path}")  # load existing ontology

# --- Proposed relation assertions (with provenance) ---
{relation_triples}

# --- Proposed dbXref annotations for mapped entities (with provenance) ---
{dbxref_triples}

g.serialize(destination="{out_ttl}", format="turtle")
print("Saved:", "{out_ttl}")
"""

def _add_relation_assertion(subject: str, predicate: str, obj: str, prov: Dict[str, Any], idx: int) -> List[str]:
    lines: List[str] = []
    assertion_id = f":rel_assertion_{idx}"
    obj_is_literal = prov.get("object_is_literal", False)
    if obj_is_literal:
        lines.append(f'g.add((URIRef("{subject}"), URIRef("{predicate}"), Literal("{obj}")))')
    else:
        lines.append(f'g.add((URIRef("{subject}"), URIRef("{predicate}"), URIRef("{obj}")))')
    lines.append(f'g.add((URIRef("{assertion_id}"), RDF.type, PROV.Entity))')
    if prov.get("source_uri"):
        lines.append(f'g.add((URIRef("{assertion_id}"), PROV.wasDerivedFrom, URIRef("{prov["source_uri"]}")))')
    agent = prov.get("agent","OntoCodexAgent")
    lines.append(f'g.add((URIRef("{assertion_id}"), PROV.wasAttributedTo, URIRef(":{agent}")))')
    if prov.get("timestamp"):
        lines.append(f'g.add((URIRef("{assertion_id}"), PROV.generatedAtTime, Literal("{prov["timestamp"]}", datatype=XSD.dateTime)))')
    if prov.get("evidence"):
        safe = prov["evidence"].replace("\\","\\\\").replace("\n"," ").replace('"', "\\\"")
        lines.append(f'g.add((URIRef("{assertion_id}"), PROV.value, Literal("{safe}")))')
    if prov.get("confidence") is not None:
        lines.append(f'g.add((URIRef("{assertion_id}"), OCXP.confidenceScore, Literal({float(prov["confidence"])}, datatype=XSD.float)))')
    return lines

def _entity_iri(base: str, label: str) -> str:
    return f"{base}{_slug(label)}"

class EnrichmentScriptAgent:
    def __init__(self, data_dir: str, memory):
        self.data_dir = data_dir
        self.memory = memory
        self.local_ns = "http://example.org/onto#"

    def _relation_triples(self, focus_iri: str, relations: List[Dict[str,Any]]) -> List[str]:
        lines: List[str] = []
        for i, rel in enumerate(relations, start=1):
            predicate = "http://purl.obolibrary.org/obo/RO_0002302" if rel.get("predicate") == "treated_with" else f"http://ontocodex.ai/rel#{rel.get('predicate')}"
            obj = rel.get("object","")
            obj_is_iri = (":" in obj or obj.startswith("http://") or obj.startswith("https://"))
            prov = {
                "source_uri": rel.get("source_uri"),
                "evidence": rel.get("evidence"),
                "agent": rel.get("agent", "KnowledgebaseAgent"),
                "timestamp": rel.get("timestamp"),
                "confidence": rel.get("final_confidence", rel.get("confidence")),
                "object_is_literal": not obj_is_iri
            }
            lines.extend(_add_relation_assertion(focus_iri, predicate, obj, prov, idx=i))
        return lines

    def _dbxref_triples(self, annotations_by_entity: Dict[str, List[Dict[str,Any]]]) -> List[str]:
        lines: List[str] = []
        idx = 1
        for label, annos in (annotations_by_entity or {}).items():
            subj = _entity_iri(self.local_ns, label)
            lines.append(f'g.add((URIRef("{subj}"), RDF.type, URIRef("http://www.w3.org/2002/07/owl#Class")))')
            lines.append(f'g.add((URIRef("{subj}"), RDFS.label, Literal("{label}")))')
            for a in annos:
                xref = f"{a.get('system')}:{a.get('code')}"
                lines.append(f'g.add((URIRef("{subj}"), OBOIO.hasDbXref, Literal("{xref}")))')
                aid = f":xref_assertion_{idx}"; idx += 1
                lines.append(f'g.add((URIRef("{aid}"), RDF.type, PROV.Entity))')
                src_file = a.get("provenance",{}).get("mapping_file")
                if src_file:
                    lines.append(f'g.add((URIRef("{aid}"), PROV.wasDerivedFrom, URIRef("file://{src_file}")))')
                agent = "TerminologyAgent"
                lines.append(f'g.add((URIRef("{aid}"), PROV.wasAttributedTo, URIRef(":{agent}")))')
                ts = a.get("provenance",{}).get("timestamp")
                if ts:
                    lines.append(f'g.add((URIRef("{aid}"), PROV.generatedAtTime, Literal("{ts}", datatype=XSD.dateTime)))')
                conf = a.get("confidence")
                if conf is not None:
                    lines.append(f'g.add((URIRef("{aid}"), OCXP.confidenceScore, Literal({float(conf)}, datatype=XSD.float)))')
        return lines

    def generate(self, ontology_context: Dict[str,Any], evidence: Dict[str,Any], mappings: Dict[str,Any], user_goal: str, disease_or_class: Optional[str] = None) -> Dict[str, Any]:
        doid_path = os.path.join(self.data_dir, "DOID.owl")
        ts = int(time.time())
        out_py = f"ontology_updates/auto_enrich_v3_{ts}.py"
        out_ttl = f"ontology_updates/auto_enrich_v3_{ts}.ttl"
        os.makedirs("ontology_updates", exist_ok=True)

        focus_iri = ontology_context.get("focus_iri") or "http://example.org/onto#Focus"
        rels = evidence.get("relations", [])
        ann_by_ent = mappings.get("annotations_by_entity", {})

        rel_lines = self._relation_triples(focus_iri, rels)
        dbx_lines = self._dbxref_triples(ann_by_ent)
        if not rel_lines:
            rel_lines = [f'# No relations extracted for {focus_iri}']
        if not dbx_lines:
            dbx_lines = [f'# No dbXref annotations to add']

        py_code = TEMPLATE_PY.format(doid_path=doid_path, out_ttl=out_ttl, relation_triples="\n".join(rel_lines), dbxref_triples="\n".join(dbx_lines))

        with open(out_py, "w", encoding="utf-8") as f:
            f.write(py_code)

        return {"script_path": out_py, "ttl_out": out_ttl, "relation_stmt_count": len(rel_lines), "dbxref_stmt_count": len(dbx_lines), "summary": "Generated relation + dbXref assertions with provenance"}
