from typing import Dict, Any, Optional, List
import os, time
from rdflib.namespace import RDFS

TEMPLATE_PY = """# Auto-generated by OntoCodex EnrichmentScriptAgent
from rdflib import Graph, URIRef, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.parse("{doid_path}")
# --- Proposed additions ---
{triples}
g.serialize(destination="{out_ttl}", format="turtle")
print("Saved:", "{out_ttl}")
"""
def _triple( subj: str, pred: str, obj: str, is_literal: bool=False ) -> str:
    if is_literal: return f'g.add((URIRef("{subj}"), URIRef("{pred}"), Literal("{obj}")))'
    return f'g.add((URIRef("{subj}"), URIRef("{pred}"), URIRef("{obj}")))'
class EnrichmentScriptAgent:
    def __init__(self, data_dir: str, memory):
        self.data_dir = data_dir
        self.memory = memory
    def _propose_triples(self, ontology_context: Dict[str,Any], evidence: Dict[str,Any], mappings: Dict[str,Any]) -> List[str]:
        triples = []
        focus = ontology_context.get("focus_iri") or ontology_context.get("focus_label")
        if not focus: return triples
        for ev in evidence.get("evidence", [])[:3]:
            if "title" in ev: triples.append(_triple(focus, str(RDFS.comment), ev["title"], is_literal=True))
        for m in mappings.get("mappings", [])[:5]:
            top = m.get("top") or {}; code = top.get("code"); table = m.get("table","").upper()
            if code and table in {"RXNORM","SNOMED","LOINC"}:
                triples.append(_triple(focus, "http://purl.obolibrary.org/obo/RO_0002302", f"{table}:{code}"))
        return triples
    def generate(self, ontology_context: Dict[str,Any], evidence: Dict[str,Any], mappings: Dict[str,Any], user_goal: str, disease_or_class: Optional[str] = None) -> Dict[str, Any]:
        doid_path = os.path.join(self.data_dir, "DOID.owl")
        ts = int(time.time()); out_py = f"ontology_updates/auto_enrich_{ts}.py"; out_ttl = f"ontology_updates/auto_enrich_{ts}.ttl"
        os.makedirs("ontology_updates", exist_ok=True)
        triples = self._propose_triples(ontology_context, evidence, mappings)
        py_code = TEMPLATE_PY.format(doid_path=doid_path, out_ttl=out_ttl, triples="\n".join(triples))
        with open(out_py, "w", encoding="utf-8") as f: f.write(py_code)
        return {"script_path": out_py, "ttl_out": out_ttl, "triples": triples, "summary": f"Generated {len(triples)} triples"}
